[config]

[templates.hyprland]
input_path = '~/.config/matugen/hyprland.conf'
output_path = '~/.cache/matugen/colors-hyprland.conf'

[templates.kitty]
input_path = '~/.config/matugen/kitty.conf'
output_path = '~/.cache/matugen/colors-kitty.conf'

[templates.rofi]
input_path = '~/.config/matugen/rofi.rasi'
output_path = '~/.cache/matugen/colors-rofi.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
